sudo: required
services:
    - docker

before_install:
    - docker build -t aparnabhure/react-test -f ./client/Dockerfile.dev ./client
    
script:
    - docker run -e CI=true aparnabhure/react-test npm test -- --coverage

after_success:
    - docker build -t aparnabhure/multi-client ./client
    - docker build -t aparnabhure/multi-nginx ./nginx
    - docker build -t aparnabhure/multi-server ./server
    - docker build -t aparnabhure/multi-worker ./worker

    # Login to docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # Take images and push to docker hub
    - docker push aparnabhure/multi-client
    - docker push aparnabhure/multi-nginx
    - docker push aparnabhure/multi-server
    - docker push aparnabhure/multi-worker

deploy:
    provider: elasticbeanstalk
    region: ap-south-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-ap-south-1-311457619630
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY    
